### ISSUE TITLE
Training Example error

### ISSUE THREAD

**Issue by photosynthesis2** [lss-1138/SegRNN#1]
Thank you for provide this codes.
But i have some error at "traing Example".

I create folder `./dataset` and place CSV files(etth1, weather).
And i run `sh scripts/SegRNN/etth1.sh`.
But i got this error: (weather file also same.)
```
Traceback (most recent call last):
  File "run_longExp.py", line 141, in <module>
    exp.train(setting)
  File "~/SegRNN/exp/exp_main.py", line 174, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark, batch_y)
  File "/home/~/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 6 were given
```
Could you please confirm this?
Any help with this issue would be appreciated.

**Comment by lss-1138** [comment]
Thank you for pointing that out.

This is because there are some conflicts in the current version of the code, which we have fixed in the **latest commit.** You can pull the latest code and rerun it, and it should work fine.

Feel free to let us know if you encounter any further issues.
