### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by YangfanOAO** [lss-1138/SegRNN#13]

**Comment by lss-1138** [comment]
您好，感谢肯定。这篇工作在投稿上不是很顺利，不过我们会努力的，谢谢。

**Comment by YangfanOAO** [comment]
可以了解下被拒的原因吗，精度已经比同方向绝大多数模型高了

**Comment by lss-1138** [comment]
之前被拒，主要是有审稿人认为没有理论解释。后面补充了理论分析，证明减少迭代次数可以减少梯度爆炸风险，又有审稿人认为这么明显的结论没有必要证明。

**Comment by YangfanOAO** [comment]
运气不行，今年必中
