### ISSUE TITLE
Shuffle is True in DataLoader

### ISSUE THREAD

**Issue by gajiMSUmm** [lss-1138/SegRNN#14]
why is the data mixed up during training? in the data_provider. this seems strange for a time series.

**Comment by lss-1138** [comment]
This is done to enhance the stability of model training. There are two key points to clarify:
1. The partitioning of training samples is performed using a sliding window along the time axis, which aligns with the characteristics of time series data.
2. The shuffle parameter in the DataLoader only randomizes the order of samples to introduce randomness during training, thereby improving the model's robustness. It does not disrupt the order of time points within each sample, so it does not violate the sequential nature of time series data.

**Comment by gajiMSUmm** [comment]
Thanks!
