### ISSUE TITLE
关于并行解码（Parallel decoding）

### ISSUE THREAD

**Issue by FranzLiszt-1847** [lss-1138/SegRNN#17]
您好，通过拜读您的文章，收获颇丰，但在阅读过程中产生一点疑惑，烦请在方便之时解答一二。
1.在论文并行解码（Parallel decoding）部分提到，将Encoding部分共享hn复制m=H/w份与PE通过GRU进行并行处理。但是由于我的模型Shape存在一点出入，故而没有将hn复制，而是直接与PE进行并行处理
` _, hy = self.rnn(pos_emb, hn)`
2.将GRU的num_layers从1改为d_model（超参数d_model在此模型中设置的比较小，一般为16）
我想知道上述改动是否会导致预测精度变差或者推理速度变慢。
因为我将SegRNN改动之后嵌入我的模型，替换原有的Encoding部分，模型时间从原来的20mins到现在的2h。但是精度略好于原有模型
由于刚开始接触此领域，很多方便不太了解，麻烦抽空帮我解答一下，不胜感激

**Comment by FranzLiszt-1847** [comment]
模型训练时间是我GPU原因，但依旧求问上述改动会影响运行速度和预测精度吗

**Comment by lss-1138** [comment]
> 1.在论文并行解码（Parallel decoding）部分提到，将Encoding部分共享hn复制m=H/w份与PE通过GRU进行并行处理。但是由于我的模型Shape存在一点出入，故而没有将hn复制，而是直接与PE进行并行处理  _, hy = self.rnn(pos_emb, hn)

如果Decoding阶段不需要分多段预测，也就是self.seg_num_y=1，这样做可以的。

> 2.将GRU的num_layers从1改为d_model（超参数d_model在此模型中设置的比较小，一般为16）

这个改动会对模型有显著影响。num_layers原来是1，改为16会显著增加了模型的深度，尤其RNN还是串行处理，这样训练时间会急剧增加。
建议不要修改num_layers。如需要调整参数，直接修改d_model来调整模型capacity即可

**Comment by FranzLiszt-1847** [comment]
好滴，感谢您的解答，不甚感激。祝学术长青
