### ISSUE TITLE
can I use this for multivariate time series classification?

### ISSUE THREAD

**Issue by suojifeng** [lss-1138/SegRNN#4]
Hi author, Is it just encoder?thank you

**Comment by lss-1138** [comment]
Hi, SegRNN is designed for long-term time series forecasting tasks. If you wish to use it for multivariate time series classification, some adjustments are necessary. For instance, you could replace the PMF module directly with a linear classification head.

Furthermore, I suggest referring to this framework (https://github.com/thuml/Time-Series-Library), which includes comprehensive implementations for forecasting, classification, anomaly detection, and other tasks. You might consider migrating the SegRNN to this repository to facilitate multivariate time series classification.
