### ISSUE TITLE
关于迭代次数 About the number of iterations

### ISSUE THREAD

**Issue by zhuoyj0599** [lss-1138/SegRNN#6]
作者您好，恭喜您这篇文章获得了极佳的效果！我关于iter有个问题：在论文中，迭代次数因划分Seg而减小为除以Seg_length，但是在实验运行过程中，我发现调整batchsize才是影响迭代次数的原因，这是为什么呢？期待您的回答！

Hello author, congratulations on the excellent results of this article! I have a question about iter: in the paper, the number of iterations is reduced to divide by Seg_length due to dividing Seg, but during the experimental run, I found that adjusting the batchsize is what affects the number of iterations, why is that? Looking forward to your answer!

**Comment by lss-1138** [comment]
您好，感谢关注。您这里指的iter和论文里所指的recurrent iterations是不一样的概念。

1. 您这里的iter，我猜测指的是训练过程中打印出来的。这里的iter是训练过程中**单个epoch所需的前向计算和反向梯度计算的次数**，即，iter数=样本总量/batchsize.
![image](https://github.com/lss-1138/SegRNN/assets/57395990/ed64044a-23c5-4361-b98e-b6d98b09ba94)


2. 论文所指的recurrent iterations是指**单样本经过segment后的在RNN内部所需的循环迭代次数**。这个指标可以通过self.seg_num_x = self.seq_len//self.seg_len计算，这个不会在训练过程中通过日志打印出来。

所以这两个是不同的概念，并不直接相关。希望我的回答有所帮助。

**Comment by zhuoyj0599** [comment]
明白了，感谢您的回答！所以还是以步长为1的滑动窗口进行取样，取完每个样本再用segment分割，我这样理解对吗？在数据量充足的情况下，是否可以尝试步长为seg_length进行取样，这样做是否能加快速度，有什么不好的效果吗？

**Comment by lss-1138** [comment]
您的理解是对的。目前的样本构造都是按步长为1滑动窗口构造的，属于数据集预处理的常规操作。【步长为seg_length进行取样】，理论上是可以的，也可以加快整个数据集的训练速度，但是这样做的后果是训练样本严重减少，导致模型训练不充分，所以一般不建议这样做。

**Comment by zhuoyj0599** [comment]
感谢您的耐心回答！

**Comment by zhuoyj0599** [comment]
还想咨询您一下，如果想改变滑动窗口的步长，需要修改哪个文件里的参数？

**Comment by lss-1138** [comment]
您好，这个需要改一下【data_provider/data_loader.py】里面的__getitem__和__len__的实现。

**Comment by zhuoyj0599** [comment]
感谢！
