### ISSUE TITLE
problem with a small dataset - illness  __len__() should return >= 0

### ISSUE THREAD

**Issue by m6129** [lss-1138/SegRNN#7]
Dear developer, I noticed that your article lacks experiments with the illness dataset.
I tried to [implement the script itself](https://www.kaggle.com/code/mrantonzaitsev/segrnn-illness-error/notebook), but I encountered an error
Could you please tell me what is the reason and how to solve this problem
```
Traceback (most recent call last):
  File "/kaggle/working/SegRNN/run_longExp.py", line 141, in <module>
    exp.train(setting)
  File "/kaggle/working/SegRNN/exp/exp_main.py", line 105, in train
    train_data, train_loader = self._get_data(flag='train')
  File "/kaggle/working/SegRNN/exp/exp_main.py", line 45, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "/kaggle/working/SegRNN/data_provider/data_factory.py", line 44, in data_provider
    print(flag, len(data_set))
ValueError: __len__() should return >= 0
...
CPU times: user 227 ms, sys: 54.7 ms, total: 282 ms
Wall time: 16.7 s
```

**Comment by lss-1138** [comment]
Thank you for bringing that up. Indeed, our article lacks experiments with the illness dataset. 

We have submitted a new version with a script specifically designed for the illness dataset, named "**scripts/SegRNN/ill.sh**". You can pull the latest code and use this script, which should address your issue. If it doesn't, please provide the script you implemented, and I'll do my best to assist you further.

**Comment by m6129** [comment]
> Thank you for bringing that up. Indeed, our article lacks experiments with the illness dataset.
> 
> We have submitted a new version with a script specifically designed for the illness dataset, named "**scripts/SegRNN/ill.sh**". You can pull the latest code and use this script, which should address your issue. If it doesn't, please provide the script you implemented, and I'll do my best to assist you further.

Thanks. I've discovered my mistake.
