### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by chartgod** [lss-1138/SegRNN#8]
You created checkpoint.pth using the etth1.csv file as training data using the run_longExp.py file.
I'm trying to predict 4 days of csv data using the learned checkpoint.pth. I want to get a source code that draws predicted data values as time series charts, can I know if you have it?

**Comment by lss-1138** [comment]
Thank you for your attention. If I understand correctly, you want to visualize the prediction results using a model trained on ETTh1 data, correct? (Predicting 4 days in ETTh1 corresponds to a prediction task with a horizon of 96 steps).

In fact, the code for visualizing prediction results exists at [line 294](https://github.com/lss-1138/SegRNN/blob/2c3ea589e92658df4738026ca09acb1988c6ac7c/exp/exp_main.py#L294) of 'exp/exp_main.py'. You can refer to this section of the code to fulfill your requirements.

**Comment by chartgod** [comment]
thx~
