### ISSUE TITLE
请问最后生成的test result范围不是原数据，像是未反归一化，哪部分参数需要重新设置呢

### ISSUE THREAD

**Issue by zhuoyj0599** [lss-1138/SegRNN#9]
![1715525867(1)](https://github.com/lss-1138/SegRNN/assets/168053066/d41114fe-1b32-43b7-8022-82d097f1d25b)

**Comment by lss-1138** [comment]
不好意思，目前代码不支持通过参数来直接控制反归一化。如果要实现反归一化，你可以尝试将data_loader.py中的self.scaler保存，然后在绘图前使用这个scaler反归一化数据。
